name: actions_on_main_branch
on: 
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:    
      - 'master'

jobs:
  pr_checks:
    runs-on: ubuntu-latest
    env:
      NAME_ADMIN: Saadi09
    steps:
      - name: st1
        if: ${{ github.actor != env.NAME_ADMIN }}
        run: exit 1
      - name: st2
        if: ${{ github.actor == env.NAME_ADMIN }}
        run: echo "ok"